// "use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavigationBar from "@/app/components/NavigationBar";
import {Footer} from "@/app/components/Footer";
import { motion } from "framer-motion";
import Head from "next/head";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SchooliFy",
  description: "Generated by create next app",
    icons: {
        icon: "logo.ico", // Path to your favicon (must be in `public/imgs/`)
    },

};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="dark">
        {/*<head>*/}
        {/*    <title>SchooliFy</title>*/}
        {/*    <meta name="description" content="An advanced Learning Management System" />*/}
        {/*    <link rel="icon" href="/imgs/logo.png" type="image/png" />*/}
        {/*</head>*/}
        <body>
        <Providers>
            {/*<div id="root">*/}
            {/*<motion.div*/}
            {/*    initial={{opacity: 0, x: -50}} // Start from the left (-X direction)*/}
            {/*    animate={{opacity: 1, x: 0}} // Move to original position*/}
            {/*    transition={{duration: 3}} // Duration of animation*/}
            {/*>*/}
            {/*    <NavigationBar/>*/}
            {/*    <div>*/}
                    {children}
            {/*    </div>*/}
            {/*    /!*</div>*!/*/}
            {/*    <Footer/>*/}
            {/*</motion.div>*/}
        </Providers>
        </body>
        </html>
    );
}
